name: stockmarketflutter
description: "A new Flutter project."

# Remove this line if you wish to publish to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^0.14.0 # Maintains compatibility with dependency_overrides
  dio: ^5.7.0
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.0
  flutter_lints: ^5.0.0
  shared_preferences:  any
  flutter_riverpod: ^2.0.0
  url_launcher: ^6.1.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/stock_logo.png"
dependency_overrides:
  http: ^0.13.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/apple.png
    - assets/images/google.png
    - assets/images/microsoft.png
    - assets/images/news1.png
    - assets/images/news2.png
    - assets/images/profile.png
    - assets/images/stock_logo.png

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir Black.ttf
          weight: 900
        - asset: assets/fonts/Avenir Light.ttf
          weight: 300
